<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <RootNamespace>SOE2D</RootNamespace>
        <SixLaborsLicenseFile>../sixlabors.lic</SixLaborsLicenseFile>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="OpenTK" Version="4.9.4" />
      <PackageReference Include="SixLabors.ImageSharp" Version="4.1.2" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="src\part\Part.SDSL.cs">
        <DependentUpon>Part.cs</DependentUpon>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <Reference Include="SDSL">
        <HintPath>..\..\SDSL\SDSL\bin\Debug\net9.0\SDSL.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
